# Generated by Django 4.0.5 on 2022-08-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, null=True)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('follower_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('twitter_count', models.IntegerField(null=True)),
                ('retweet_count', models.IntegerField(null=True)),
                ('last_tweet', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=10, null=True)),
                ('profile_name', models.CharField(max_length=30, null=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.position')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('height', models.CharField(max_length=2000, null=True)),
                ('weight', models.CharField(max_length=2000, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.city')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.offer')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.position')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.highschool')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.year')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='team',
            field=models.ManyToManyField(to='data.team'),
        ),
        migrations.CreateModel(
            name='Hardcommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(max_length=100)),
                ('recruited_by', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.team')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.state'),
        ),
    ]
